version: "3.8"

services:

 mysql:
   image: mysql
   container_name: mysql
   environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=expenses_tracker
   ports:
    - "3306:3306"
   volumes:
    - my-vol:/var/lib/mysql
   networks:
    - my-net
   restart: always

 java_app:
   build:
      context: ./
   container_name: Expensetracker
   environment: 
    - SPRING_DATASOURCE_USERNAME=root
    - "SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/expenses_tracker?allowPublicKeyRetrieval=true&useSSL=false"
    - SPRING_DATASOURCE_PASSWORD=root
   ports:
    - "8080:8080"
   networks:
    - my-net
   depends_on:
    - mysql
   restart: always


networks:
  my-net:


volumes:
   my-vol:
